# Generated by Django 3.1.1 on 2020-10-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='Mobile', max_length=13)),
                ('status', models.CharField(choices=[('1', 'New Client'), ('2', 'Client In Progress'), ('3', 'Client Processed')], default='1', max_length=9)),
            ],
        ),
    ]
