# Generated by Django 3.1.1 on 2020-10-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(default='Mobile', max_length=13, unique=True),
        ),
    ]
