# Generated by Django 3.1.1 on 2020-10-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='progress',
            field=models.CharField(choices=[('1', 'New Client'), ('2', 'Client In Progress'), ('3', 'Client Processed')], default='1', max_length=9),
        ),
    ]
