# Generated by Django 3.1.1 on 2020-10-12 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Title', max_length=64)),
                ('email', models.CharField(default='Title', max_length=64)),
                ('password', models.CharField(default='Title', max_length=64)),
                ('is_able', models.BooleanField()),
                ('is_admin', models.BooleanField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
