# Generated by Django 3.1.1 on 2020-10-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='client_id',
            new_name='client_email',
        ),
    ]
