# Generated by Django 3.1.1 on 2020-10-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerAdmin', '0002_auto_20201012_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='client_email',
            new_name='client_id',
        ),
    ]
