# Generated by Django 3.1.1 on 2020-10-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerAdmin', '0004_auto_20201012_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='is_able',
        ),
    ]
